name: Build DonutCore JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download Spigot API
      run: |
        mkdir -p lib
        wget -O lib/spigot-api.jar https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.16.5-R0.1-SNAPSHOT/spigot-api-1.16.5-R0.1-20210804.142908-1.jar 

    - name: Compile Plugin
      run: |
        mkdir -p build
        javac -d build -cp lib/spigot-api.jar donutcore/DonutCore.java

    - name: Package JAR
      run: |
        cd build && jar cfe ../DonutCore.jar donutcore.DonutCore .
        cp ../plugin.yml build/
        cd build && jar uf ../DonutCore.jar plugin.yml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DonutCore
        path: DonutCore.jar
